{{- include "sch.config.init" (list . "ibmElasticsearch.sch.chart.config.values") -}}
{{- if or (.Values.rbac.create) (not (tpl .Values.rbac.serviceAccountName .)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sch.names.fullName" (list .) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list .) | indent 4 }}
subjects:
  - kind: ServiceAccount
    {{- if eq (tpl .Values.rbac.serviceAccountName .) "" }}
    name: {{ include "sch.names.fullName" (list .) | quote }}
    {{- else }}
    name: {{ (tpl .Values.rbac.serviceAccountName .) | quote }}
    {{- end }}
roleRef:
  kind: Role
  name: {{ include "sch.names.fullName" (list .) | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}