{{- include "sch.config.init" (list . "ibmElasticsearch.sch.chart.config.values") -}}
  {{- if .Values.ingress.enabled -}}
  {{- $fullName := include "elasticsearch.uname" . -}}
  {{- $servicePort := .Values.httpPort -}}
  {{- $ingressPath := .Values.ingress.path -}}
apiVersion: {{ template "elasticsearch.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "sch.names.fullCompName" (list . .sch.chart.components.ingress) | quote }}
  labels:
  {{ include "sch.metadata.labels.standard" (list .) | indent 4 }}
  {{- with .Values.ingress.annotations }}
annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
tls:
  {{- range .Values.ingress.tls }}
- hosts:
  {{- range .hosts }}
  - {{ . }}
  {{- end }}
  secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
rules:
  {{- range .Values.ingress.hosts }}
- host: {{ . }}
  http:
    paths:
      - path: {{ $ingressPath }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
  {{- end }}
  {{- end }}