{{- include "sch.config.init" (list . "ibmElasticsearch.sch.chart.config.values") -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "sch.names.fullCompName" (list . .sch.chart.components.headless) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" ( list . .sch.chart.components.headless) | indent 4 }}
spec:
  clusterIP: None # This is needed for statefulset hostnames like elasticsearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
{{ include "sch.metadata.labels.standard" (list . .sch.chart.components.esServer) | indent 4 }}
  ports:
  {{- if not .Values.useSSLProxy }}
  - name: {{ .Values.service.httpPortName | default "http" }}
    port: {{ .Values.httpPort }}
  - name: {{ .Values.service.transportPortName | default "transport" }}
    port: {{ .Values.transportPort }}
  {{- else }}
  - name: ssltransport
    port: {{ .Values.proxyTransportPort }}
  {{- end }}
