{{- include "sch.config.init" (list . "ibmElasticsearch.sch.chart.config.values") -}}
{{- if or (.Values.rbac.create) (not (tpl .Values.rbac.serviceAccountName .)) -}}
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
{{- if tpl .Values.global.imagePullSecret . }}
  - name: {{ tpl .Values.global.imagePullSecret . }}
{{- end }}
metadata:
  name: {{ include "sch.names.fullName" (list .) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list . ) | indent 4 }}
{{- end -}}
