{{- include "sch.config.init" (list . "ibmElasticsearch.sch.chart.config.values") -}}
  {{- if .Values.esConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sch.names.fullName" (list .) | quote }}
  labels:
{{ include "sch.metadata.labels.standard" (list .) | indent 4 }}
data:
{{- range $path, $config := .Values.esConfig }}
  {{ $path }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}